CREATE TABLE IdRelations(childId BIGSERIAL NOT NULL UNIQUE PRIMARY KEY, parentId BIGSERIAL NOT NULL);
CREATE TABLE IdData(id BIGSERIAL NOT NULL UNIQUE PRIMARY KEY, relativePath TEXT NOT NULL, type VARCHAR);
CREATE TABLE CreationTimeTable(id BIGSERIAL NOT NULL UNIQUE PRIMARY KEY, creationTime BIGSERIAL);