CREATE TABLE IdRelations(childId BIGINT NOT NULL UNIQUE PRIMARY KEY, parents BIGINT[] NOT NULL, basicId BIGINT NOT NULL);
CREATE TABLE IdData(id BIGINT NOT NULL UNIQUE PRIMARY KEY, relativePath TEXT NOT NULL, type VARCHAR);
CREATE TABLE CreationTimeTable(id BIGINT NOT NULL UNIQUE PRIMARY KEY, creationTime BIGINT);
-- server data --
CREATE TABLE ServerData(serverId BIGINT NOT NULL UNIQUE PRIMARY KEY, url TEXT, metaData JSON); --TODO:ADD DATA
CREATE TABLE ServerIdDiapasons(serverId BIGINT NOT NULL PRIMARY KEY, fromId BIGINT UNIQUE, toId BIGINT UNIQUE);